title: Your Lack of Title is Disturbing
author: Darth Vader
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Join us at Dark Side Saloon.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
